### ISSUE TITLE
Index taker in LogFill event

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/contracts#110]
Currently only `maker` and `feeRecipient` are indexed in the `LogFill` event of the Exchange contract. Any objections to also index `taker`?

**Comment by berndbohmeier** [comment]
How is this done in 0x?

**Comment by berndbohmeier** [comment]
There can be only three values marked as indexed. So I guess that is the reason why this is not indexed. 
But as we now index the event ourselves, this is not an issue anymore, we can just also index the taker if we want to. 
I would close this here as we could only add indexed if we would remove it from another field, and open a new issue on the relay .

**Comment by dakingha69** [comment]
Ah ok didn't know there can only be three indexed values. Ok will close this issue and open a new one in the relay repo.
