### ISSUE TITLE
transferring negative value

### ISSUE THREAD

**Issue by schmir** [trustlines-network/contracts#138]
I'd like to introduce the possibility of  transferring negative values (given certain constraints, in this case that the source and target are the same). This would help with closing a trustline with positive balance, i.e. we could use the same code in the relay server to determine a payment path regardless of the balance being positive or negative.

Disregarding ABI compatibility issues changing the right variables to a signed type and checking for source and target being the same would be enough to implement it.

The alternative would be to transfer a positive value with the partner address being the second one in the payment path. That's a bit harder to implement and may not even be possible in the general case when we introduce interests (because we cannot be sure when the transaction is being executed on chain).

(Speaking of interests we may have to introduce a dedicated function that handles interests to close a trustline anyway).

@cducrest @berndbohmeier Do you have any objections or opinions?

**Comment by berndbohmeier** [comment]
I see how that would make it possible but this is not the point of this. The point is to use existing payment methods to allow that. For the mediators this is just a normal transfer, they dont see the constraint. So we would need to solve that they should get fees for that as for a normal payment, but then I dont see the difference to just doing the payment in reverse. The solution for this could be, and we had that already, to allow the possibility that the fees are payed by the receiver.

**Comment by schmir** [comment]
We decided to do the transfers in reverse  and let the receiver pay, so I'm closing this one.
