### ISSUE TITLE
BalanceUpdate misses the information who paid for the fees

### ISSUE THREAD

**Issue by schmir** [trustlines-network/contracts#148]
`_mediatedTransferReceiverPays` uses the same event like _mediatedTransfer. The `BalanceUpdate` event does not contain a field, which describes who paid for the fees.

We should either add a field to `BalanceUpdate`, which says who paid for the fees or use another similar event in `_mediatedTransferReceiverPays` that is being used when the  receiver pays.

The first option has the problem of not being backwards compatible, but could be extensible (e,g, in case we implement something like both receiver and sender paying equal amounts).

**Comment by berndbohmeier** [comment]
BalanceUpdate only indicated a change in balance, so this is not the place to think about fees. 
It is not a problem to calculate from the events we have who payed what fee, so I would not add that in the contracts, but in the relay server.

**Comment by schmir** [comment]
I think the `TransferEvent` should include the information, who paid for the transfer. Why wouldn't we want to have it there?
 
For the `BalanceUpdate` I'm fine with not having it, so closing this issue.
