### ISSUE TITLE
Create DEX contract

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#2]
## Requirement:
- Allow to buy/sell ETH for trustline money.
- Allow to buy/sell any token for trustline money.
- Seller can be offline

## Implementation:
Use a standard exchange contract, which works with ERC20 `approve` and `transferFrom`.  Reason, we can a) reuse existing code b) symmetry between buying/selling. Drawback is higher cost. 

WIP! there is no symmetry!

### Exchanging ERC20 tokens for TL money
Alice sell A tokens for TL tokens, Bob buys A tokens paying with TL tokens.
- Alice `approve`s the DEX to transfer `bid_amount` A tokens
- Alice sends `offer` and offers `bid_amount` A tokens for `ask_amount` B tokens
- Bob `approve`s  `ask_amount` B tokens to the exchange  `buy`s offer by referencing it
  - `transferFrom` Bob

### Exchanging ETH for TL money
send ETH to an ERC20_ETH wrapper contract. like above afterwards.

```
.init(currency_network_address)		
.offer(bid_amount,	ask_amount)	
.buy	offer_id(buy_quantity, via[])
.cancel(offer_id)
via[]: path between buyer and seller
```

## init
stores `owner`, `CurrencyNetwork.address`

## offer
payable function

**Comment by berndbohmeier** [comment]
Use 0x protocol. Change the exchange contract where necessary to support transferFrom with maxfee and path.

**Comment by berndbohmeier** [comment]
Done
