### ISSUE TITLE
CurrencyNetwork fees are not calculated correctly

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#20]
Unittests of the former `tl_business_token` wrt. fees don't run. 

fees calculation include: outstandingFees of user A and B, network fee, rebalance fees.

**Comment by heikoheiko** [comment]
they don't include interest?

**Comment by heikoheiko** [comment]
see #26

**Comment by heikoheiko** [comment]
see https://github.com/trustlines-network/project/issues/14 Transfer Fee Schedule

**Comment by berndbohmeier** [comment]
Outdated
