### ISSUE TITLE
Is onboarding a bundled transaction in Smart Contract Layer?

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#22]
Currently the steps for onboarding are executed in several transactions in the frontend.

The onboarding could go to an other layer, ie. the Smart Contract Layer, to facilitate one transaction logic.

Pro: onboarding is a real transaction and cannot fail partially
Con: redundant logic in Smart Contract

**Comment by heikoheiko** [comment]
Solution: no. Alice onboards Bob. Alice does three independent transactions 1) send ETH to Bob's EOA 2) create Bob's UserAccount with Bob as owner. 3) Offers a creditline for Bob.
