### ISSUE TITLE
Registry of Onborder-Onborded relations

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#23]
**Requirement**

Onboarding should be possible without the onboarded party to be indebted.
To compensate for this ETH-gift a referral reward will be introduced. 

**Solution**

To facilitate referral rewards the `CurrencyNetwork` contract must provide a mapping to store who onboarded whom.

**Comment by heikoheiko** [comment]
There is not 0ETH onboarding. What we discussed was wether the onborded party should be indebted with the ETH amount he received from the onboarder. The referral rewards are independent from this. They've just been used as an argumentation, why an onborder would be willing to gift ETH. Also there is no "guarantee".

**Comment by ice09** [comment]
replaced see #29
