### ISSUE TITLE
UserAccount must support initializations with owner_address

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#24]
*A user wants to join a network. To join, he has to pay ETH for onboarding transactions.*

To facilitate free onboarding for the onboarded the `userProxy` must be created by the _onboarder_.
The onboarder creates Proxy and Controller contract for _onboarded_ directly and pays for it. He gets rewarded at a later point of time by referrals.

**Comment by heikoheiko** [comment]
what is the controller contract? later rewards is part of the user story. this issue actually should be about: `UserProxy must support initializations with owner_address`, i.e. we must support, that UserProxies are instantiated through transactions which are not sent by the owner.

**Comment by ice09** [comment]
In `RecoverableController` the `_userKey_` can be set by the creator of the contract.
