### ISSUE TITLE
CurrencyNetwork.transfer must support path

### ISSUE THREAD

**Issue by heikoheiko** [trustlines-network/contracts#25]
`.transfer(to, value, via_obj)`
with
`via_obj: [max_fee, [hops, ]]`

Please see this: https://docs.google.com/spreadsheets/d/1fLAwMk734yBGXSI0j440c-4kcZ0S0sDAV8B_dWIBH8M/edit#gid=0

**Comment by ice09** [comment]
was introduced in 085eb5dc8a2935a745b6b768d45ada8718882d12
