### ISSUE TITLE
CurrencyNetwork.transfer support for receiving the exact amount at target

### ISSUE THREAD

**Issue by heikoheiko** [trustlines-network/contracts#26]
Rationale: Due to fees, the sent amount != received amount. This is very different from traditional token contracts. Contract interoperability requires, that the receiving contract receives exactly the requested amount. Therefore `transfer(A, 10)` will lead to more than 10 being deducted from the sender (exception being if it gets credited interest higher than the transfer fees). 

Solution: Calculate and apply the transfer from the receiver towards the sender.

**Comment by ice09** [comment]
so this means that `transfer(A, 10)` has to do two calculations:

```
transfer(A,10):
  realValue = calculateFees(A, 10, _preparedPath);
  for (i in path):
    _transfer(i._to, realValue);
    realValue -= calculateFees(realValue, i._balanceAB);
```

**Comment by berndbohmeier** [comment]
Done. receiveid amount will be at least what he wanted to send him, sometimes more because of fees.
