### ISSUE TITLE
Check Transfer Gas Cost

### ISSUE THREAD

**Issue by heikoheiko** [trustlines-network/contracts#28]
compare with old repo:
https://github.com/brainbot-com/trustlines/issues/28

fee schedule:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/opcodes.py

**Comment by ice09** [comment]
Using this calculation method:

```
trxid = trustlines_contract.transact({"from":A}).echo()
trx = web3.eth.getTransaction(trxid)
print(message, trx["gas"])
```

the result (reoccurring) for this noop-function:

```
function echo() {
    ///noop
}
```

is always 121660 gas usage which doesn't make sense.
