### ISSUE TITLE
Existing creditline limits can be reduced by debtor

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#30]
Currently, the `updateCreditline` request has to be accepted by the debtor, by calling `acceptCreditline`, to avoid someone going into debt without approval by the debtor.

In exception to this rule, the creditor must always be able to reduce the creditline given to the debtor without approval by the debtor.

Relates to #34 currently even without approval creditor cannot reduce creditline below balance.

**Comment by heikoheiko** [comment]
Clarification, this is about credit line limits, not interest. Let's make this distinction explicitly. 

I don't think this is an exception of the rule, that the receiver of a creditline needs to confirm creditline limit updates. 


Possible Credit Line Limit Updates (Creditline from Alice for Bob):
- Alice creates or increases creditline limit
   - Bob needs to confirm
- Alice reduces (incl. setting to zero) the creditline limit (no confirmation needed)
- Bob reduces the creditline (no confirmation needed)

**Comment by ice09** [comment]
was solved with b28102d
