### ISSUE TITLE
Access Control of registerPath

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#32]
Before a transfer the user should be able to specifiy `maxFee`. Nobody other than the sender should be able to specify `maxFee` to avoid an attacker to overwrite a already specified `maxFee` with a more costly path.

**Comment by heikoheiko** [comment]
What fees are we talking about? What motivates the requirement? Where is maxFee set and used?

**Comment by heikoheiko** [comment]
I assume the issue is about who's allowed to register a path. The key of a path is `H(sender + receiver)`. Only sender is allowed to register a path.

**Comment by ice09** [comment]
Is value not part of the key of path, as the path can be different of different values?

**Comment by heikoheiko** [comment]
> Is value not part of the key of path,
no. it's assumed, that paths are short lived. expiresOn is not necessary. the client will clean up. 

pattern is:
- goal, pay a smart contract using approve/transferFrom pattern
- set path
- approve
- call contract
- contract transfer(s)From
- approve(0)
- del path

**Comment by ice09** [comment]
was solved with b28102d
