### ISSUE TITLE
Check necessity for expiresOn for cheques

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#33]
Is `expiresOn` really necessary? What use does it have except specifying the path. If the path on real usage is not valid anymore, it just wouldn't work.

Pro:
- The idea is to be able to remove the entries

Con:
- Extra storage

**Comment by heikoheiko** [comment]
Link to "cheques" specification? I don't understand what is meant by "specifying the path". Why is there a path in cheques? 

Yes, the smart contracts need to keep a list of all cashed cheques to avoid double cashing. Therefore they need to have an expiration date.
