### ISSUE TITLE
Emit event when cash cheque was successful

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/contracts#35]
Currently there is no event when a cheque was successfully cashed.

**Comment by ice09** [comment]
is ` event ChequeCashed(address indexed _sender, address indexed _receiver, uint32 indexed _value);` ok?

**Comment by dakingha69** [comment]
does it make sense to also add the field `_expiresOn`?

**Comment by ice09** [comment]
for me not, I can add it if necessary, but why do we need it if the cheque is cashed?

**Comment by ice09** [comment]
will close for now, event was added.
