### ISSUE TITLE
Add timestamp to events

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/contracts#37]
We need timestamp for events:
- Transfer
- BalanceUpdate
- CreditlineUpdateRequest
- CreditlineUpdate
- ChequeCashed

**Comment by ice09** [comment]
ok, how should the timestamp look like, just `now`, so `uint(256)`?

**Comment by dakingha69** [comment]
yes that should suffice.

**Comment by dakingha69** [comment]
ok no need to add timestamps to events. we will determine it in relay server from the block
