### ISSUE TITLE
Add LICENSE for project

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#43]
There are several projects included with different licenses, at least

1. ERC223 Standard Implementation: https://github.com/Dexaran/ERC223-token-standard (GPLv3)
2. EtherRouter: https://github.com/ownage-ltd/ether-router (MIT)
3. SafeMath: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/math/SafeMath.sol (MIT)
4. ECVerify: https://gist.github.com/axic/5b33912c6f61ae6fd96d6c4a47afde6d (no license)
5. SimpleMultiSig: https://github.com/christianlundkvist/simple-multisig (no license)

Trustlines should be licensed under MIT.

**Comment by ice09** [comment]
All 5 libraries are now published using the MIT. Will update project accordingly:

- [ ] create LICENSE.md in root, stating this project is MIT
- [ ] list all other used MIT projects
- [ ] link to MIT license
- [ ] add copyrights to all files (esp. ECVerify)

**Comment by ice09** [comment]
created PR https://github.com/trustlines-network/contracts/pull/46

**Comment by berndbohmeier** [comment]
Done
