### ISSUE TITLE
Create CurrencyNetworkFactory contract

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#5]
*As a user, I want to create a new CurrencyNetwork for my own token.*

## Requirements

- set parameters: maxFees, maxInterest, ERC20-related: name, abbrev?
- deposit?

Allows to create new CurrencyNetworks.

- [x] clarify input parameters
- [x] register CurrencyNetwork at Registry
- [x] clarify who and how a CN can be created (Deposit)

**Comment by ice09** [comment]
- [ ] clarify input parameters

**Comment by heikoheiko** [comment]
> As a user, I want to create a new CurrencyNetwork for my own token.
not supported atm. see #14 

> maxFees, maxInterest
fee factors are a global param, so there is no `max`
maxInterest is not supported yet in the CurrencyNetwork contract. defer this

**Comment by berndbohmeier** [comment]
deferred
