### ISSUE TITLE
Shall we enforce, that an address is only valid in one currency network?

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#9]
**Solution: one address (user-account) can be used in several currency networks**

A user does have an `app-account` which can be exchanged in the `chain-account` in the Blockchain. One `chain-account` can be in several currency networks (separate registry necessary). The app does _not_ support several `chain-accounts` in one currency network and does _not_ support  several `app-accounts` in one `chain-account`.

**Comment by ice09** [comment]
- [ ] get a going-in position on this question
- [ ] sync with dhkim's analysis and user stories

**Comment by ice09** [comment]
Solution: one address (user-account) can be used in several currency networks

**Comment by heikoheiko** [comment]
Resolved: accounts can be used in multiple CurrencyNetworks
